server:
  port: 7777

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/alert
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql